### ISSUE TITLE
Add option to show event start time on calendar page.

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#100]
Customer asks: Can the start time show on the Monthly calendar?

ref: https://secure.helpscout.net/conversation/379726259/60884/?folderId=875342

**Comment by pippinsplugins** [comment]
Seems like a good option.

**Comment by JJJ** [comment]
In the `release/2.0` branch, we do this in `wp-admin` and that will carry over to how we draw calendars theme-side also, but those implementation details are TBD and probably need their own issues once they're farther along.

So, the functionality now exists, it just needs to go back in with widgets and shortcode support.

**Comment by JJJ** [comment]
This will get tackled as part of #158.

Also, we generally are including more accurate descriptors from my old WP Event Calendar plugin.

Closing this out in favor of that WIP.
