### ISSUE TITLE
2 Week and 1 Week calendars do not show correct date

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#114]
2 Week and 1 Week calendars do not show correct date when the start date is set to "Monday".

<img width="1034" alt="screen shot 2017-09-05 at 3 04 04 pm" src="https://user-images.githubusercontent.com/290886/30081099-7ef913e4-924b-11e7-98b6-0c9722736a22.png">

ref: https://secure.helpscout.net/conversation/425960648/66083/?folderId=875342

**Comment by JJJ** [comment]
Fixed in `release/2.0`.
