### ISSUE TITLE
If Start of Week is Monday - Week and Two week calendars show wrong day of the week

### ISSUE THREAD

**Issue by gspice** [sugarcalendar/sugar-event-calendar#122]
From HS ticket:
https://secure.helpscout.net/conversation/425960648/66083?folderId=1909447

Re-tested with:  1.6.6

**To recreate:** 
* Go to Events > Settings - set `Start of Week` to `Monday` (works correct if set to default of `Sunday`)
* Create a new page using shortcodes `[sc_events_calendar type="week"]` or `[sc_events_calendar type="2week"]` and you'll notice the day of the week is ahead of the numeric date by one:

For example, today is Friday March 23rd and it shows it to be Saturday:

![start-day-monday-off-by-one](https://user-images.githubusercontent.com/3018245/37851878-c15fb302-2e9d-11e8-9fd1-19801b18c2ee.png)

The `Month` view shows the days of the week on the correct numeric day.

**Comment by gspice** [comment]
Oops, looks like this was fixed on #114 ?

**Comment by pippinsplugins** [comment]
Yep!
