### ISSUE TITLE
Add class to calendar cells that contain events

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/sugar-event-calendar#124]
It would be really nice to have a CSS class on calendar cells for the cells that have events in them. That would allow someone to target just the calendar days that are not empty.

Here's one customer that would like this: https://secure.helpscout.net/conversation/546194085/78769?folderId=1909453

**Comment by JJJ** [comment]
I _think_ I’ve done this for 2.0, but I’ll confirm.

**Comment by JJJ** [comment]
Classes are `empty` and `not-empty` respectfully.

Also added are `count-%` where `%` is the literal number of items in the table cell.

I kept these "type agnostic" so the word "event" was purposely omitted from class names, for future calendar reuse in ways that are not event specific.

Marking as fixed, for `release/2.0`.
