### ISSUE TITLE
2.0: All event URLs show home page

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/sugar-event-calendar#146]
All of the event pages show the home page instead of the requested event page.

This includes:
- single event pages
- event post type archive
- calendar taxonomy term archives

**Comment by JJJ** [comment]
The post type and taxonomy are still private.

Related to #142 and #134.

**Comment by JJJ** [comment]
Made these public. For testing purposes, permalink settings will need to be visited and saved to refresh them after updating.
