### ISSUE TITLE
2.0: Gray background width is wrong

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/sugar-event-calendar#147]
![image](https://user-images.githubusercontent.com/1034109/48779780-05237d80-ec9e-11e8-9e86-fa401964945c.png)

The gray behind the `Repeat` and `End Repeat` looks clearly wrong. Not sure if the intention was for it to be the width of the labels or less.

**Comment by JJJ** [comment]
I think the tab body must be missing a background color.

Do EDD3 reports & customers have the same issue?

**Comment by pippinsplugins** [comment]
No, EDD 3.0 reports show properly for me.

**Comment by pippinsplugins** [comment]
Ubuntu 18.04 with Chrome.
