### ISSUE TITLE
2.0: Replace Posts_List_Table with Events

### ISSUE THREAD

**Issue by JJJ** [sugarcalendar/sugar-event-calendar#153]
The `list` view currently relies on the `WP_Posts_List_Table` class, which has a few flaws:

* It automatically pulls from `wp_posts` instead of `wp_sc_events`
* It does not provide us a way to list events by a date range; only paginate them
* It shows events for the events post-type only (see #134 for other concerns)
* It's the only UI that includes bulk actions, which _might_ be nice later, but is a lot to take on now
* We'd need to hardcode a goofy `JOIN` to make column sorting work right
* Taxonomy filtering uniquely works with this out of the box, which is nice
----

After playing with this for dozens of hours now, I think it would be a better UX to override this list table entirely and pull information directly from the `wp_sc_events` database table instead.

We are already doing something similar via `sugar_calendar_posts_extra_tablenav()` to cram the event filter UI above it. We'd take it a step further and override this screen a bit sooner, negating the aforementioned cramming.

I haven't coded this yet, and it's probably 2-3 hours work to finish.

**Comment by pippinsplugins** [comment]
I agree on replacing it with our own. We've done that quite a few times in our various plugins when the list table isn't flexible enough.

Are you also suggesting moving the event data out of wp_posts and into a custom table?

**Comment by JJJ** [comment]
This is _basically_ done. More work is happening via #157 and #158..
