### ISSUE TITLE
2.0: datepicker styles messed up

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/sugar-event-calendar#165]
On the event add new screen, the datepickers are messed up for me:

<img width="926" alt="screen shot 2019-01-22 at 3 57 17 pm" src="https://user-images.githubusercontent.com/1034109/51568200-c9a05d80-1e5e-11e9-8207-8ca4c70ed2f8.png">

Two things:

1. Clearly the CSS isn't working quite right
2. Can we please disable the Chrome autofill?

I've tried refreshing CSS but that's not fixing it.

**Comment by JJJ** [comment]
@pippinsplugins can you checkout `issue/165` and confirm fixed? I wasn't able to duplicate _exactly_ what you show off here, but I remembered you reporting something similar in EDD3 originally, so I took a stab at it.

**Comment by JJJ** [comment]
<img width="656" alt="screen shot 2019-01-22 at 10 59 20 pm" src="https://user-images.githubusercontent.com/88951/51584083-5cf68480-1e99-11e9-8f1d-a2e11cc9b522.png">

**Comment by pippinsplugins** [comment]
Styles look good now but I'm still seeing auto complete in Chrome:
![image](https://user-images.githubusercontent.com/1034109/51611321-94d6e980-1ee4-11e9-9dc7-2fc239b2f25b.png)

**Comment by pippinsplugins** [comment]
Nvm, ignore that, wrong branch :D

Looks good, merging.
