### ISSUE TITLE
2.0: event details missing from single event page

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/sugar-event-calendar#169]
None of the event details (save for the description) are showing on the single event page:
![image](https://user-images.githubusercontent.com/1034109/51615202-e2575480-1eec-11e9-9d6b-b07f16635cf2.png)
![image](https://user-images.githubusercontent.com/1034109/51615212-e5eadb80-1eec-11e9-885f-53a4cb571318.png)

**Comment by JJJ** [comment]
Confirmed. Still using the old post meta functions. Will fix today.

**Comment by JJJ** [comment]
Fixed and merged via #180.
