### ISSUE TITLE
2.0 event migration not moving events

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/sugar-event-calendar#170]
The 2.0 DB migration appears to have not worked for me. Everything ran and acted like it worked but none of the previous events show up in the list table.
![image](https://user-images.githubusercontent.com/1034109/51615717-28f97e80-1eee-11e9-84e8-89b4ef747c40.png)
There should be three events but only one `Test` shows up, which was created post migration.

Interestingly, the legacy events that were supposed to have been migrated do show up in the event list widget.

![image](https://user-images.githubusercontent.com/1034109/51615704-1f701680-1eee-11e9-809b-3010edb1d833.png)

**Comment by JJJ** [comment]
Confirmed. Fix imminent.

**Comment by JJJ** [comment]
Fixed and merged.

Some old meta-data still needs to be mapped to the new columns. That'll happen in #148.
