### ISSUE TITLE
2.0: Database not always created during upgrade

### ISSUE THREAD

**Issue by pippinsplugins** [sugarcalendar/sugar-event-calendar#171]
I tested the upgrade routine and it appears that no database was created.

Here's the tables in my site:
<img width="368" alt="screen shot 2019-01-23 at 10 33 24 am" src="https://user-images.githubusercontent.com/1034109/51621586-7845ac00-1efa-11e9-953c-f23fc9ab288b.png">

This explains why none of my event meta is saving on one of my installs.

Related to #170 and #148

**Comment by JJJ** [comment]
Fixed and merged.
