### ISSUE TITLE
Review Widget requests.

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#55]
See if these can be worked into plugin or have a way to extend plugin to make these available.

1. A custom widget to list events in our format.

2. Handle the dates as a range. We don’t display the times since most of them are all-day events anyway.

3. A place to enter a URL to override the link. If we don’t supply a URL then the post title links to the full post, as usual. We use this to link directly to an event page with a signup, for example, instead of repeating all the details in the event post. It saves a click and duplication of information when we’re hosting our own events and want minimal friction to get signed up.

4. A place to enter a city, state, and maybe country, which get displayed. I thought about using the maps add on for this but it just takes an address as a single line and passes it to Google. I think it would be more reliable to specify the individual fields of data rather than parse those out of one address string.

5. “Sonya will be presenting a two-day conference” is the post excerpt or part before the <!—more—> tag. We like to use that to output just a little bit of info in the widget while still having a longer description in the full post.

6. A link to the full schedule list since we typically only display a certain number of events. I think that goes to the post archive page now.

**Comment by JJJ** [comment]
All of these are more easily achieved beyond 2.0, thanks to the multitude of enhancements and upgrades that in provides.

Many of these make sense as potential add-ons. External linking, Enhanced maps, Schedule blocks, etc... so I'm closing this 1 issue, labelling it, and we can revisit any these independently in the future.

**Comment by douglsmith** [comment]
Just noting that @growdev originally captured these from my feedback on things I was trying to accomplish. I'll see how 2.0 shapes up then create individual issues for consideration for whatever is still relevant.
