### ISSUE TITLE
Start of Week dropdown has all 7 days

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#66]
But, the code only works for Sunday/Monday.

Either change code to work for all days, or remove options from dropdown.

@pippinsplugins thoughts?

**Comment by growdev** [comment]
@pippinsplugins  I've removed Tuesday - Saturday as options on this drop down.

Should I add an upgrade routine for anyone who might have been using "Wednesday" as a start of week?

**Comment by pippinsplugins** [comment]
Yes, let's go ahead and add an upgrade routine for this.

**Comment by JJJ** [comment]
`release/2.0` works for all days, obeying the `start_of_week` option from WordPress core.
