### ISSUE TITLE
Recurring events can recur indefinitely 

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#73]
In current version the "recur until" field is not required. This means that an event can recur indefinitely which is a challenge for calculating lists of events.

We need to either 1. require this field so we have a finite list to calculate/work with, or 2. set a limit like "2 years" that will be quietly imposed by the plugin.  I prefer the first option.

@pippinsplugins thoughts?

![recur](https://cloud.githubusercontent.com/assets/290886/22657912/bc2f84ee-ec5d-11e6-8a0a-ea3aa129ccdb.jpg)

**Comment by pippinsplugins** [comment]
I vote for option 1 as well. Could we include a checkbox for `Forever` to make the UI simpler for people that do want forever events?

**Comment by JJJ** [comment]
`release/2.0` has some work to do around this also, so moving this there.

**Comment by JJJ** [comment]
Indefinitely recurring events will not be an issue in 2.0 and beyond. The meta-box UI is working. TBD is where and how exactly to reveal this info (some is done where it already had made sense.)
