### ISSUE TITLE
Show Recurring events in archive view

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#74]
The archive view (example https://sugarlocal.com/events/ ) should show recurring events in the list of posts. 

from #48: 

>I think you'd need to hook into pre_get_posts, perform a look up with sc_get_all_events(), extract the post IDs, then set post__in. Essentially duplicating the queries.
>
>Let's go ahead and punt the archive view so we can get this finished up.

**Comment by JJJ** [comment]
The CPT approach here has gone stale (custom tables will make this easier.)

Let's close this out in favor of #155 and others.
