### ISSUE TITLE
Show recurring events in admin area

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#86]
Possibly show recurring event data in the Events list.

Original request: "would be awesome to see recurring event data in the admin area and set ordering based on when the event is. currently you can’t really tell when a recurring event is going to happen in the admin, you can only see in frontend."

![slack-imgs](https://cloud.githubusercontent.com/assets/290886/24172826/b3edefa2-0e57-11e7-92e6-f3a8dab2a55e.png)

**Comment by pippinsplugins** [comment]
How about we add a `Recurs` column?

**Comment by growdev** [comment]
Customer:  "Yes, that'll work. "

**Comment by pippinsplugins** [comment]
👍

**Comment by JJJ** [comment]
`release/2.0` has a Recurring column in the list table, and all calendar views include both all-day, multi-day, and recurring events.
