### ISSUE TITLE
Verify recurring events with no 'recur until' work as expected

### ISSUE THREAD

**Issue by growdev** [sugarcalendar/sugar-event-calendar#91]
Daniel: Check the output of test script.

Update: It doesn't.  `sc_calculate_recurring()` works while `$until > $current` and if there is no `$until` then only one occurrence (the first occurrence) is recorded.

We need to decide how these are saved and when they would need to be recalculated.

**Comment by JJJ** [comment]
Recurring event saving/querying is done via the custom `wp_events` database table in `release/2.0`.
